refactor: sd as 18 decimals
sablier-labs/flow pull request #312
Opened 2024-10-15 11:38 UTC by andreivladbrg

Closes https://github.com/sablier-labs/flow/issues/302

2024-10-15 12:57 UTC, andreivladbrg commented
@smol-ninja nevermind for now the fail inv test, we will change the `eq` to `ineq` as we decided in https://github.com/sablier-labs/flow/issues/307

2024-10-15 14:19 UTC, smol-ninja requested changes

2024-10-15 14:19 UTC, smol-ninja commented on src/libraries/Helpers.sol
> +    /// @notice Descales the provided `amount` to be denoted in the token's decimals.
```suggestion
    /// @notice Descales the provided `amount` from 18 decimals fixed-point number to token's decimals fixed-point number.
```

2024-10-15 14:19 UTC, smol-ninja commented on src/libraries/Helpers.sol
> +        if (decimals > 18) {
No need to have `>` in this. Otherwise it goes against the natspecs and we would have to descale amount to 18 decimals if `decimals > 18`

```suggestion
        if (decimals == 18) {
```

2024-10-15 14:19 UTC, smol-ninja commented on src/libraries/Helpers.sol
> +    /// @dev The following logic is used to denormalize the amount:
We can remove `dev` comment. Instead of that how about adding comments inside the logic i.e. over `if` and over `unchecked`.

2024-10-15 14:19 UTC, smol-ninja commented on src/libraries/Helpers.sol
> +    function scaleAmount(uint256 amount, uint8 decimals) internal pure returns (uint256) {
Same suggestions as above.

2024-10-15 14:19 UTC, smol-ninja commented on src/SablierFlow.sol
> +        ongoingDebt = Helpers.descaleAmount({
Whats the point of returning `ongoingDebt` as descaled but `snapshotDebt` as scaled? We should return `ongoingDebt` as scaled version so that the following holds true.

`Helpers.descale(ongoingDebt + snapshotDebt) == totalDebt`

Otherwise, it can return false. Because if  `ongoingDebt` is descaled, it would introduce precision error to above calculations.

And for this to work, no need to change `ongoingDebt` to `scaledOngoingDebt` for public function. Similar to how we mention that `getSnapshotDebt` returns value in 18-decimal format, we can do the same for `ongoingDebt` function.

2024-10-15 14:19 UTC, smol-ninja commented on src/SablierFlow.sol
> +    function _scaledOngoingDebtOf(uint256 streamId) internal view returns (uint256) {
If we agree to returning 18 decimal value in `ongoingDebt`, we can keep it as `_scaledOngoingDebtOf`

2024-10-15 14:46 UTC, andreivladbrg commented on src/SablierFlow.sol
> +        ongoingDebt = Helpers.descaleAmount({
> Whats the point of returning ongoingDebt as descaled but snapshotDebt as scaled?

i had these three reasons in mind: 
- consistency over "debt" calculation functions
- no point to return an amount of _calculated_ "debt" _externally_ that cannot transferred
- Razvan made a point to have them return only in token's decimals IIRC (will ask again)

but this makes sense and i tend to agree:
> as scaled version so that the following sanity check holds true.
> Helpers.descale(ongoingDebt + snapshotDebt) == totalDebt

2024-10-15 14:55 UTC, smol-ninja commented on src/SablierFlow.sol
> +        ongoingDebt = Helpers.descaleAmount({
Thanks for sharing the reasons. Just a comment below.

> no point to return an amount of calculated "debt" externally that cannot transferred

Since we are returning `snapshotDebt` in 18 decimal already, its not true anymore. An external actor may not have this information that `ongoingDebt` is being calculated during runtime whereas `snapshotDebt` is a stored in slots. So imo the consistency is when we return all debts in the same decimal format including totalDebt. But then it creates a poor DX because `totalDebt` and `balance` are required to be compared to understand the stream's solvency.

Now, since `snapshotDebt` and `ongoingDebt` are like two saiyans and both of them are required to form a super saiyan called `totalDebt`, it would be a good idea to return `snapshotDebt` and `ongoingDebt` in 18 decimal atleast so people know these two are linked to each other.

2024-10-15 15:26 UTC, andreivladbrg commented on src/SablierFlow.sol
> +        ongoingDebt = Helpers.descaleAmount({
as discussed on slack, we will rename the function to `ongoingDebtScaled`, and the `snapshotDebt` to `snapshotDebtScaled`

2024-10-15 15:31 UTC, smol-ninja commented on src/SablierFlow.sol
> +        ongoingDebt = Helpers.descaleAmount({
and variables as well.

> What if we rename `snapshotDebt` to `snapshotDebtScaled` and `ongoingDebt` to `ongoingDebtScaled` everywhere and provide no function that return descaled versions of these two, because if we do, then it again bring in the same confusion that equality wont hold true between these two and `totalDebt`.

- Always use `ongoingDebtScaled` and `snapshotDebtScaled` names when referring to ongoing debt and snapshot debt related functions and variables to represent them in 18-decimals fixed-point numbers
- Don't offer descaled getters for them to avoid any confusion to users.

cc @razgraf

2024-10-15 21:07 UTC, smol-ninja requested changes
Thank you for making all these changes. Clearly this is a big PR and has more impacts than I imagined. A few comments:

- I can see two variations of `scaled` naming: `scaledABC` and `abcScaled`. I suppose you are using `abcScaled` for function names (`ongoingDebtScaledOf` and `getSnapshotDebtScaled`) whereas `scaledABC` for variables names. If so, there are inconsistencies at a few places such as use of `snapshotDebtScaled` variable in `getSnapshotDebtScaled` function. Lets stick to one convention so that there is no confusion when deciding for a variable names that requires 18 decimal format. 

My suggestion would be to either use `scaledABC` format or `ABCScaled` format for all variables and function naming and not both. Whats your preference?

- Would it be more consistent if we use the same naming convention for snapshot debt getter as well i.e. `snapshotDebtOf` similar to `ongoingDebtOf`? Its the only function that looks out of touch since it leans more towards getters defined in `ISablierFlow` than `ISablierFlowBase`. If you are aligned, we can consider refactoring it in the next release of Flow.

2024-10-15 21:13 UTC, smol-ninja commented
One more comment: Technical doc is now outdated given that `sd` has been refactored to follow 18 decimal format. What do we do about it now? Here are some of the ideas:

- Lets remove numbers from it as it would require to be re-calculated.
- Only adds theory and formula as its easy to do.

Wdyt? if you think you want it to have numbers as well then we will have to update them as well as charts (I suppose charts are outdated too right?)

2024-10-16 11:10 UTC, andreivladbrg commented
> * can see two variations of `scaled` naming: `scaledABC` and `abcScaled`

actually, my intention was to only have one, and that is `abcScaled`. the only exception, as you mentioned, is `ongoingDebtOf`, which would indeed end up in a situation where the function would have a sounded weird, "ongoingDebtOfScaled".

> My suggestion would be to either use scaledABC format or ABCScaled format for all variables and function naming and not both. Whats your preference?

ofc, we should have just one, as said above. how would you keep consistency and still have a good function name? my preference is `abcScaled`

> snapshotDebtOf similar to ongoingDebtOf

i think that would be misleading. snapshot debt is a state variable, while the other is a function that calculates an amount in real time. we should definitely keep the "get" keyword for all getters, as it only reads a state, and having "Of" points out that it’s different from the classic getters (dynamic function)

2024-10-16 11:14 UTC, smol-ninja commented
> actually, my intention was to only have one, and that is abcScaled. 

Got it. Then lets use `abcScaled` everywhere, and for ongoing debt, we can use `ongoingDebtScaledOf`.

2024-10-16 11:14 UTC, andreivladbrg commented on tests/integration/concrete/pause/pause.t.sol
> +        uint256 expectedSnapshotDebt = flow.ongoingDebtScaledOf(defaultStreamId);
> Wouldn't the correct approach here be to assign expectedSnapshotDebt to flow.getSnapshotDebtScaled(streamID) + flow.ongoingDebtScaledOf(streamId) since after pause, sd would get incremented by od?

techincally yes, but this a _concrete_ test, we should have actually only "contrete" values to test them, since the `sd` is now normalized we can use `ONE_MONTH_DEBT_18D`

your approach is ideal in an inv/fuzz environment IMO

2024-10-16 11:19 UTC, smol-ninja commented on tests/integration/concrete/pause/pause.t.sol
> +        uint256 expectedSnapshotDebt = flow.ongoingDebtScaledOf(defaultStreamId);
But you did not use `ONE_MONTH_DEBT_18D` instead `flow.ongoingDebtScaledOf`.

2024-10-16 11:20 UTC, andreivladbrg commented on tests/integration/concrete/pause/pause.t.sol
> +        uint256 expectedSnapshotDebt = flow.ongoingDebtScaledOf(defaultStreamId);
Yes, mb, I should change this, will push

2024-10-16 12:53 UTC, andreivladbrg commented on tests/integration/concrete/total-debt-of/totalDebtOf.t.sol
> +        assertEq(ONE_MONTH_DEBT_18D, snapshotDebtScaled, "total debt");
correct

2024-10-16 13:01 UTC, smol-ninja commented on tests/integration/concrete/total-debt-of/totalDebtOf.t.sol
> +        assertEq(ONE_MONTH_DEBT_18D, snapshotDebtScaled, "total debt");
"it" implies the function that the test is written for. In this case, its `totalDebtOf`

> it should return snapshot debt

This means that `totalDebtOf` should return snapshot debt.

> it should return the sum of snapshot debt and ongoing debt

This means that `totalDebtOf` should return snapshot debt + ongoing debt.

2024-10-16 13:17 UTC, andreivladbrg commented on tests/integration/concrete/total-debt-of/totalDebtOf.t.sol
> +        assertEq(ONE_MONTH_DEBT_18D, snapshotDebtScaled, "total debt");
updated in 663e9e83b41e3d206a64cb5e1d40ce37adc8cb65

2024-10-16 13:17 UTC, andreivladbrg commented on tests/integration/concrete/pause/pause.t.sol
> +        uint256 expectedSnapshotDebt = flow.ongoingDebtScaledOf(defaultStreamId);
663e9e83b41e3d206a64cb5e1d40ce37adc8cb65

2024-10-16 13:30 UTC, smol-ninja requested changes
Last few suggestions then looks good here.

2024-10-16 13:30 UTC, smol-ninja commented on src/SablierFlow.sol
> +        uint256 scaledBalance = Helpers.scaleAmount({ amount: balance, decimals: tokenDecimals });
`balanceScaled`

2024-10-16 13:30 UTC, smol-ninja commented on src/SablierFlow.sol
> +        uint256 scaledTotalDebt = _ongoingDebtScaledOf(streamId) + _streams[streamId].snapshotDebtScaled;
`totalDebtScaled`

2024-10-16 13:30 UTC, smol-ninja commented on src/SablierFlow.sol
> +        uint256 scaledOngoingDebt = _ongoingDebtScaledOf(streamId);
`ongoingDebtScaled`

2024-10-16 13:30 UTC, smol-ninja commented on src/SablierFlow.sol
> +        uint256 scaledAmount = Helpers.scaleAmount(amount, tokenDecimals);
`amountScaled`

2024-10-16 13:30 UTC, smol-ninja commented on tests/integration/concrete/ongoing-debt-of/ongoingDebtOf.t.sol
I renamed it to `ongoingDebtScaledOf.t.sol` in my commit which has now been overridden so it has been reverted back. It should be `ongoingDebtScaledOf.t.sol`

2024-10-16 13:30 UTC, smol-ninja commented on tests/integration/concrete/ongoing-debt-of/ongoingDebtOf.tree
same renaming of file here.

2024-10-16 13:30 UTC, smol-ninja commented on tests/integration/concrete/total-debt-of/totalDebtOf.tree
> +   │  └── it should return the
error here.

2024-10-16 13:30 UTC, smol-ninja commented on tests/integration/fuzz/ongoingDebtOf.t.sol
file name here.

2024-10-16 13:42 UTC, smol-ninja approved these changes
Fanstatic. Less goooo 🚀

2024-10-16 13:49 UTC, merged