docs: refactor technical doc
sablier-labs/flow pull request #314
Opened 2024-10-16 10:18 UTC by smol-ninja

Refactors technical doc in line with https://github.com/sablier-labs/flow/pull/312.

2024-10-16 10:19 UTC, PaulRBerg commented on TECHNICAL-DOC.md
> +The debt is tracked using "snaoshot debt" and "snapshot time". At snapshot, the following events are taking place:
typo

2024-10-16 17:13 UTC, andreivladbrg requested changes
> the unlock interval takes into account the last withdraw time ($wt$) and not snapshot time ($st$) anymore. Thats what the PR is about.

I don’t understand this very well. Can you please rephrase it? 
As far as I can see, I think you wanted to change how we refer to the moment in time `t`. Changing `st` to `wt` is not precisely correct. For example, these constant intervals are not correct, as the constant interval starts from st up to the moment the withdrawal happened:

https://github.com/sablier-labs/flow/blob/cf2a59f9015314ae2533bf5e0f16fb2ad54e9964/TECHNICAL-DOC.md?plain=1#L393-L395


> Without changing the numbers we can say that time values are considered since last withdraw time and not the last snapshot time

The number shouldn’t be changed—the delay in the current example (`rps = 0.000000_011574e18`) should remain the same.

> This will require updating the charts with the new labels

correct, will do

> This is due to the fact that with numbers and charts, the cost of maintenance of the technical doc is non-zero. The purpose of the doc is to explain delays and precision issues in calculations of withdrawn amount which imo is already well explained. 

The fact that the maintenance is non-zero is correct. I believe having concrete examples and clear graphs in our theory section will help external readers understand the delay issue more quickly and effectively. For us, it took a while to precisely understand what was actually happening, so I believe the cost is worth it to minimize future questions about the technical part.

2024-10-16 17:58 UTC, smol-ninja commented on TECHNICAL-DOC.md
> +delay &= t - wt - \frac{R_\text{td}}{rps} - 1 \\
Yeah agree to remove it.

2024-10-16 17:58 UTC, smol-ninja commented on TECHNICAL-DOC.md
> +   $\text{ongoing debt} = rps \times (\text{block timestamp} - \text{snapshot time})$.
sounds good.

2024-10-23 10:20 UTC, smol-ninja commented
@andreivladbrg do you remember what we discussed about it last week? I forgot to make notes and now can't recall what we decided about this doc.

2024-10-23 20:00 UTC, smol-ninja commented
@andreivladbrg I have made the suggested changes. Let me know if it looks good now.

2024-10-24 14:56 UTC, andreivladbrg commented
@smol-ninja as discussed on slack, we should remove everything from this line and below https://github.com/sablier-labs/flow/blob/4c198886f80a472aec17f3a54b55830f1a29e961/TECHNICAL-DOC.md?plain=1#L215

since there is no more delay due to sd in 18 decimals, also it can be proved by these equality checks in the PR: https://github.com/sablier-labs/flow/pull/320

2024-10-24 15:04 UTC, smol-ninja commented
Not that line. MVT is one of the two problems that led us to use 18-decimal fixed-point number for rps and sd. Everything [from here](https://github.com/sablier-labs/flow/blob/docs/technical-doc/TECHNICAL-DOC.md#delay-due-to-descaling) should be deleted.

2024-10-24 16:00 UTC, smol-ninja commented on tests/integration/concrete/withdraw-delay/withdrawDelay.t.sol
> +/// @dev A series of demonstrative tests that help to understand prove the absence of delay in the withdrawal process.
If something is not present, why should we have tests to prove its absence? Also the equality in https://github.com/sablier-labs/flow/pull/320 is sufficient to prove that streaming works as expected.

2024-10-24 16:04 UTC, smol-ninja commented on TECHNICAL-DOC.md
lets add a subheading to distinguish it from the problems section.

### Conclusion

or 

### Solution

2024-10-24 16:09 UTC, andreivladbrg commented on TECHNICAL-DOC.md
7a2693ea8ff8ecb3fa69fba6bb970c73d870d0d0

2024-10-24 16:10 UTC, andreivladbrg commented on tests/integration/concrete/withdraw-delay/withdrawDelay.t.sol
> +/// @dev A series of demonstrative tests that help to understand prove the absence of delay in the withdrawal process.
I am thinking of a way to mention these in the docs
but not yet sure, so i would temporarily keep them

wdyt?

2024-10-24 16:14 UTC, smol-ninja commented on tests/integration/concrete/withdraw-delay/withdrawDelay.t.sol
> +/// @dev A series of demonstrative tests that help to understand prove the absence of delay in the withdrawal process.
We started with an implementation that had these problems and required us to explain it. And then we solved them. So if you think from a fresh perspective, this problem does not exist.

So for someone looking at the code with fresh mind, the explanations in technical doc and the assumption in security is sufficient. I think this contract is no longer required.

2024-10-24 16:14 UTC, andreivladbrg commented on tests/integration/concrete/withdraw-delay/withdrawDelay.t.sol
> +/// @dev A series of demonstrative tests that help to understand prove the absence of delay in the withdrawal process.
fair enough

2024-10-24 16:15 UTC, andreivladbrg commented on tests/integration/concrete/withdraw-delay/withdrawDelay.t.sol
> +/// @dev A series of demonstrative tests that help to understand prove the absence of delay in the withdrawal process.
aa97ca0b087d9f93c36f1f4f3798a31caccf0562

2024-10-24 16:25 UTC, smol-ninja reviewed
looks good to me now.

2024-10-24 19:44 UTC, andreivladbrg approved these changes
lessss gooo, no more delay 🚀🚀

2024-10-24 19:44 UTC, merged