test: use inequality in inv test
sablier-labs/flow pull request #315
Opened 2024-10-16 13:53 UTC by andreivladbrg

Closes https://github.com/sablier-labs/flow/issues/307

2024-10-16 14:23 UTC, smol-ninja commented on tests/invariant/Flow.t.sol
> +                    "Invariant violation: total debt + withdrawn amount must be at most 3 units greater than total streamed amount with delay"
Why 3? I suppose it was failing for 2? If so, lets change it to 10 because it can fail at 3 as well. 

Also, as mentioned in [issue](https://github.com/sablier-labs/flow/issues/307), why not compare `totalStreamedAmount` with `flow.totalDebtOf(streamId) + flowStore.withdrawnAmounts(streamId)` instead of `totalStreamedAmountWithDelay`?

The purpose of `totalStreamedAmountWithDelay` was to not have this inequality but now since we are moving towards inequality, it would be more accurate invariant to confirm that actual streamed is within 10 wei of total streamed as a good assumption.

Because if we compare `totalStreamedAmountWithDelay` with `totalDebtOf + withdrawnAmounts` which is actual streamed, the deviation from `totalStreamed` can be bigger than the delta of 3.

2024-10-16 15:31 UTC, andreivladbrg commented on tests/invariant/Flow.t.sol
> +                    "Invariant violation: total debt + withdrawn amount must be at most 3 units greater than total streamed amount with delay"
> Why 3? I suppose it was failing for 2? If so, lets change it to 10 because it can fail at 3 as well.

nope, it was not failing for 2. all the CI invariants that failed (for those I found) had only a difference of 1. it uses the amount calculated including the delay, which theoretically should be equal. the reason for the failure is that we take the delay from the $t$ moment instead of calculating it from $t_0$ to $t$, which completely shifts it to the right

2024-10-17 13:59 UTC, smol-ninja requested changes

2024-10-17 13:59 UTC, smol-ninja commented on tests/invariant/Flow.t.sol
> +                assertLe(
I wonder why is there an "`Le`" here? Previously, we had the following relations:
1. $totalStreamedAmount \ge totalStreamedAmountWithDelay$
2. $totalStreamedAmountWithDelay = totalDebt + totalWithdrawn$

Therefore from the above two, the new relation should be
- $totalStreamedAmount \ge totalDebt + totalWithdrawn$

and not the opposite.

2024-10-17 14:03 UTC, smol-ninja approved these changes

2024-10-17 14:25 UTC, smol-ninja commented on tests/invariant/Flow.t.sol
> +                assertLe(
https://github.com/sablier-labs/flow/pull/315/commits/45436e9cbf3ff149f5f3f8f7bc059b91ffdaaa94

2024-10-17 14:25 UTC, merged