test: use equality in the withdraw multiple test
sablier-labs/flow pull request #320
Opened 2024-10-24 13:41 UTC by andreivladbrg

This is just a test to see if the delay still exists after the change of `sd` to 18 decimals

2024-10-24 16:23 UTC, smol-ninja requested changes
Excellent observation @andreivladbrg. Left some comments below.

2024-10-24 16:23 UTC, smol-ninja commented on tests/integration/fuzz/withdrawMultiple.t.sol
1. Can you also please update the checklist? It still mentions "less than".
2. What about updating `testFuzz_WithdrawMultiple_Usdc_SmallDelay` as well?

2024-10-24 16:23 UTC, smol-ninja commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
Why removed the selector? The goal was to test both.

2024-10-24 16:23 UTC, smol-ninja commented on tests/invariant/Flow.t.sol
> +    /// debt and withdrawn amount.
It should be "equal" only here now.

2024-10-24 16:23 UTC, smol-ninja commented on tests/invariant/Flow.t.sol
Could you also update the invariant section in the docs?

2024-10-24 19:27 UTC, andreivladbrg commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
no, the idea was to use equality in assertion, and if we keep the simple `withdraw` we can't achieve this

2024-10-24 19:37 UTC, andreivladbrg commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
also, what is the point of using `withdraw`  if we want to test if there is delay?

2024-10-24 20:54 UTC, smol-ninja commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
One reason why `withdraw` was included in this test was to make sure the actual streamed amount never exceed desired streamed amount i.e. no leaking of funds when rps is unrealistic. Previously, there were cases when `withdraw` was causing more delay than `withdrawMax` depending on with what amount and at what time you call them.

Therefore, even if there is no delay anymore, it may be a good idea to ensure that in case of `withdraw` the actual withdrawn is less than or equal to desired withdrawn. So this would solve the problem that we cant achieve equality in case of `withdraw`.

`withdraw` and `withdrawMax` can behave differently because one uses value of `coveredDebt` and another one takes input from user.

2024-10-24 20:59 UTC, smol-ninja requested changes

2024-10-24 20:59 UTC, smol-ninja commented on tests/integration/fuzz/withdrawMultiple.t.sol
>          // Assert that actual withdrawn amount is always less than the desired amount.
This comment requires update.

2024-10-24 20:59 UTC, smol-ninja commented on tests/invariant/Flow.t.sol
[Technical doc](https://github.com/sablier-labs/flow/blob/test/delay-fix/TECHNICAL-DOC.md) needs to have updated invariant as well.

2024-10-25 10:44 UTC, smol-ninja commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
On this @andreivladbrg, if you think that testing `withdrawMax` for errors also tests `withdraw` implicitly, then lets go with your changes. Otherwise, we should test for `withdraw` as well.

2024-10-25 10:57 UTC, andreivladbrg commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
> it may be a good idea to ensure that in case of `withdraw` the actual withdrawn is less than or equal to desired with

well, ofc, but if the bounded amount is going to be 1, it for sure going to be lower than the lower bound :))
the point think you are missing, the param amount in the function cannot be greater than `coveredDebt` as we have other [concrete test](https://github.com/sablier-labs/flow/blob/004a94be20765ea8e5f90ba280bde510bc2cf972/tests/integration/concrete/withdraw/withdraw.t.sol#L96-L133) for it. and here, once again, we are testing if there is no delay (equality)

> anymore, it may be a good idea to ensure that in case of withdraw the actual withdrawn is less than or equal to desired withdrawn

we have a sum of withdrawn amounts. if the maximum possible scenario of this sum (only `withdrawMax` calls) equals the total amount streamed it implicitly test that the sum of bound amounts between `[1,max withdrawable]` (we were using `bound(withdrawAmount, 1, flow.withdrawableAmountOf)`) will always be lower or equal to total, thus introducing this test does not add value in what this new file should test "NoDelay" but it test other thing, i.e. withdraw param is lower than covered debt, which is also in this [invariant test](https://github.com/sablier-labs/flow/blob/dabed1f2bd219653bbe59a3f8813f2ad3daa396c/tests/invariant/Flow.t.sol#L337) and in the concrete tests mentioned above

lmk if it makes sense

2024-10-25 11:30 UTC, smol-ninja commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
You convinced me on "param amount in the function cannot be greater than `coveredDebt`". Good point.

2024-10-25 11:32 UTC, smol-ninja approved these changes
Good to go. I left a comment below in case you want to address it.

2024-10-25 11:32 UTC, smol-ninja commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
Lets remove the private function and add the logic directly to `testFuzz_WithdrawMaxMultiple_RpsWideRange_NoDelay`

2024-10-25 11:35 UTC, andreivladbrg commented on tests/integration/fuzz/withdrawMultiple.t.sol
> +        _test_WithdrawMultiple(rps, withdrawCount, timeJump, decimals, 0);
good point, will update

2024-10-25 11:42 UTC, merged