test: add getters tests
sablier-labs/flow pull request #321
Opened 2024-10-26 13:33 UTC by andreivladbrg

Closes https://github.com/sablier-labs/flow/issues/299

I decided not to create separate dirs for each individual getter function to avoid a lengthy folder structure in the test. I find the organization clearer this way, as each getter function has a straightforward purpose: to read a value from storage. Although this approach doesn’t strictly follow the BTT pattern, I believe it’s acceptable. 

For amount getters (`bal`, `rps`, `sd`), there are two tests: one for when the amount is zero and another for when it is non-zero. The same applies to boolean getters, with tests for both `false` and `true` states.

2024-10-28 20:47 UTC, smol-ninja requested changes
Nice work on the PR. Very sorry I took so long to mention that bulloak supports multiple functions in the same test suite.

```tree
SablierFlowBase_Getters::getBalance
├── given null
│  └── it should revert
└── given not null
   ├── given zero
   │  └── it should return zero value
   └── given not zero
      └── it should return non-zero value


SablierFlowBase_Getters::isPaused
├── given null
│  └── it should revert
└── given not null
   ├── given true
   │  └── it should return true value
   └── given not true
      └── it should return false value
```

and then if you run 

```shell
bulloak scaffold -wf tests/integration/concrete/getters/getters.tree
```

it will generate a single contract to test all these getters. We wont have to make separate directories for each function without losing on BTT. I am in favour of keeping BTT for the same because it makes it easier to see whats tests and whats not. Let me know what you think.

2024-10-28 20:47 UTC, smol-ninja commented on tests/integration/concrete/getters/getters.t.sol
There are other getters as well. So how about being more explicit with the name here with `flowbase-getters/flowBaseGetters.t.sol`?

2024-10-28 21:25 UTC, andreivladbrg commented on tests/integration/concrete/getters/getters.t.sol
which one? are you saying that the function that calculate an amount (refundable/withdrawable) are also getter?
IMO i wouldn't call them getters only because they are _constant_ functions

2024-10-28 21:25 UTC, andreivladbrg commented
> bulloak supports multiple functions in the same test suite

ah lol, how did i not know?

> I am in favour of keeping BTT

now i’m in favor as well

2024-10-28 21:30 UTC, smol-ninja commented on tests/integration/concrete/getters/getters.t.sol
You are right. They are not getters. lets keep it as `getters/getters.t.sol`

2024-10-29 11:14 UTC, andreivladbrg commented
@smol-ninja updated the branch with the `.tree` file

2024-10-29 16:23 UTC, smol-ninja approved these changes
Thank you for the changes. Lesss go 🚀

2024-10-29 17:05 UTC, merged