feat: add eth fees in flow functions
sablier-labs/flow pull request #348
Opened 2024-12-13 16:30 UTC by andreivladbrg

Closes #328

2024-12-13 18:35 UTC, PaulRBerg requested changes
Thanks Andrei.

Good idea to write concrete tests, but it's overkill to test these things:

- it should update the caller ETH balance
- it should update the flow contract ETH balance

Just having the call compiling with the `{ value } ` option would be enough. We are not meant to test that the EVM is implemented correctly.

So let's please simplify those tests.

2024-12-14 14:39 UTC, smol-ninja requested changes
This PR should be created against a new branch called `staging`.

2024-12-14 14:39 UTC, smol-ninja commented on tests/fork/Flow.t.sol
> +        vm.deal({ account: sender, newBalance: sender.balance + FEE });
Can we deal enough ETH to `sender` in Base contract to avoid dealing in each test?

2024-12-14 14:48 UTC, smol-ninja requested changes
Sorry, I accidentally clicked submit review. Here is full review.

2024-12-14 14:48 UTC, smol-ninja commented on tests/fork/Fork.t.sol
> +        vm.deal({ account: sender, newBalance: sender.balance + FEE });
Same as https://github.com/sablier-labs/flow/pull/348#discussion_r1885083619. If we can deal enough ETH to sender through Base, we can remove this line.

2024-12-14 14:48 UTC, smol-ninja commented on tests/integration/concrete/collect-fees/collectFees.tree
> +├── when admin is not contract
should be `given` because `admin` is a contract state and not a user input.

2024-12-14 14:48 UTC, smol-ninja commented on tests/integration/concrete/collect-fees/collectFees.t.sol
> +        resetPrank({ msgSender: users.admin });
Since this is common across all tests here, lets move this to `setUp`.

2024-12-14 14:48 UTC, smol-ninja commented on tests/integration/concrete/collect-fees/collectFees.t.sol
> +        flow.withdrawMax{ value: FEE }({ streamId: defaultStreamId, to: users.recipient });
How about moving this to set up function? Withdraw leads sends fee to the contract and then collect fee is called by the admin. So it should be a part of the setup which sets up the testing scenario and then in test functions, we just test `collectFees`.

2024-12-14 14:48 UTC, smol-ninja commented on tests/integration/concrete/payable/payable.t.sol
> +contract Payable_Integration_Concrete_Test is Shared_Integration_Concrete_Test {
The fork test that you have modified also cover this particular scenario. If any of the functions misses `payable`, the fork tests would fail. So imo we can remove it.

2024-12-14 14:50 UTC, andreivladbrg commented on tests/integration/concrete/payable/payable.t.sol
> +contract Payable_Integration_Concrete_Test is Shared_Integration_Concrete_Test {
The fork tests do not cover all 15 unique functions

2024-12-14 14:51 UTC, andreivladbrg commented on tests/integration/concrete/collect-fees/collectFees.tree
> +├── when admin is not contract
Should be updated in lockup as well, then

2024-12-14 14:51 UTC, andreivladbrg commented on tests/fork/Flow.t.sol
> +        vm.deal({ account: sender, newBalance: sender.balance + FEE });
The sender is fuzzed in create, we don't have an unique sender

2024-12-14 14:56 UTC, smol-ninja commented on tests/integration/concrete/payable/payable.t.sol
> +contract Payable_Integration_Concrete_Test is Shared_Integration_Concrete_Test {
You are right.

2024-12-14 14:58 UTC, smol-ninja commented on tests/integration/concrete/payable/payable.t.sol
> +        assertEq(users.sender.balance, initialSenderBalance - FEE);
Based on https://github.com/sablier-labs/flow/pull/348#discussion_r1885087102, this test is good for me. But should we remove assertions? If a function does not have `payable`, `success` would not be `true`. So no need to check for balances.

2024-12-14 14:58 UTC, smol-ninja commented on tests/integration/concrete/collect-fees/collectFees.tree
> +├── when admin is not contract
Yes. But we can do that later in lockup.

2024-12-14 15:00 UTC, smol-ninja commented on tests/fork/Flow.t.sol
> +        vm.deal({ account: sender, newBalance: sender.balance + FEE });
Can we fund the fuzzed sender right after it is created? After `checkUsers(params.recipient, params.sender);` line?

2024-12-14 17:07 UTC, andreivladbrg commented on tests/fork/Flow.t.sol
> +        vm.deal({ account: sender, newBalance: sender.balance + FEE });
yeah, we could, correct

2024-12-14 17:17 UTC, andreivladbrg commented
> Good idea to write concrete tests, but it's overkill to test these things:
it should update the caller ETH balance
it should update the flow contract ETH balance
Just having the call compiling with the { value }  option would be enough. We are not meant to test that the EVM is implemented correctly.

thanks. fair, let's remove them. also, does it mean we should remove the `address.balance` check from all places?

2024-12-14 18:39 UTC, andreivladbrg commented
@PaulRBerg @smol-ninja updated the branch with your feedback, lmk if it looks good

2024-12-15 07:31 UTC, smol-ninja approved these changes
LGTM.

2024-12-16 04:44 UTC, merged